const GITHUB = 'https://github.com/Tharusha101/agentmirror';
const NPM = 'https://www.npmjs.com/package/agentmirror';
const PLAYGROUND = `${GITHUB}/tree/main/apps/playground`;
const MIGRATE = `${GITHUB}/blob/main/docs/migrating-to-agents-md.md`;

const steps = [
  {
    cmd: 'agentmirror init',
    text: 'Create a canonical AGENTS.md (import your existing CLAUDE.md or .cursorrules). You curate it — never auto-generated.',
  },
  {
    cmd: 'agentmirror sync',
    text: 'Generate every tool mirror from it — real files, cross-platform, no symlinks.',
  },
  {
    cmd: 'agentmirror check',
    text: 'A CI gate that fails when a mirror drifts or a rule points at a file or script that no longer exists.',
  },
];

const formats = [
  ['Claude Code', 'CLAUDE.md'],
  ['Cursor', '.cursor/rules/agents.mdc'],
  ['GitHub Copilot', '.github/copilot-instructions.md'],
  ['Gemini CLI', 'GEMINI.md'],
  ['Windsurf', '.windsurfrules'],
  ['Cline', '.clinerules'],
];

const AGENTS_SAMPLE = `# Acme Widgets — Agent Guide

## Conventions
- Indent with spaces (2).
- Entry point is \`src/index.ts\`.`;

const CLAUDE_SAMPLE = `<!-- Generated by agentmirror from AGENTS.md.
     Do not edit directly. -->

# Acme Widgets — Agent Guide

## Conventions
- Indent with spaces (2).
- Entry point is \`src/index.ts\`.`;

function Pill({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded-full border border-[#1e2533] px-3 py-1 text-xs text-[#9aa3b5]">
      {children}
    </span>
  );
}

export default function Home() {
  return (
    <div className="mx-auto max-w-6xl px-6">
      {/* Nav */}
      <header className="flex items-center justify-between py-5">
        <div className="flex items-center gap-2.5 font-bold tracking-tight">
          <span className="glow text-xl text-[#00e6c3]">▦</span>
          AgentMirror
        </div>
        <nav className="flex items-center gap-5 text-sm text-[#9aa3b5]">
          <a className="hover:text-[#00e6c3]" href={PLAYGROUND}>Playground</a>
          <a className="hover:text-[#00e6c3]" href={GITHUB}>GitHub</a>
          <a className="hover:text-[#00e6c3]" href={NPM}>npm</a>
        </nav>
      </header>

      {/* Hero */}
      <section className="py-16 text-center sm:py-24">
        <div className="mb-5 flex justify-center gap-2">
          <Pill>AGENTS.md standard</Pill>
          <Pill>open source · MIT</Pill>
        </div>
        <h1 className="mx-auto max-w-3xl text-4xl font-extrabold leading-tight tracking-tight sm:text-6xl">
          One <span className="glow text-[#00e6c3]">AGENTS.md</span>,<br />
          synced to every AI coding tool.
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg text-[#9aa3b5]">
          Stop copying the same rules into CLAUDE.md, .cursorrules, and copilot-instructions
          until they drift apart. Keep one canonical file; AgentMirror generates the rest and
          fails CI when they fall out of sync.
        </p>

        <div className="mx-auto mt-8 inline-flex items-center gap-3 rounded-lg border border-[#1e2533] bg-[#0e1219] px-4 py-3 font-mono text-sm">
          <span className="text-[#6b7488] select-none">$</span>
          <code className="text-[#d7dce5]">npm install -g agentmirror</code>
        </div>

        <div className="mt-8 flex flex-wrap justify-center gap-3">
          <a
            href={GITHUB}
            className="btn-neon rounded-lg bg-[#00e6c3] px-5 py-2.5 font-semibold text-[#08221e] hover:brightness-110"
          >
            Get started
          </a>
          <a
            href={PLAYGROUND}
            className="rounded-lg border border-[#2a3346] px-5 py-2.5 font-semibold text-[#d7dce5] hover:border-[#00e6c3]"
          >
            Try the playground →
          </a>
        </div>
      </section>

      {/* Problem */}
      <section className="border-t border-[#1e2533] py-16">
        <h2 className="text-2xl font-bold">The problem: format fragmentation</h2>
        <p className="mt-3 max-w-2xl text-[#9aa3b5]">
          Every tool wants its own context file. Teams using more than one copy the same rules
          into several — and they drift apart within weeks. Symlinks break on Windows and in CI.
        </p>
        <div className="mt-8 grid gap-3 sm:grid-cols-3">
          {formats.map(([tool, file]) => (
            <div key={file} className="card rounded-xl p-4">
              <div className="text-sm text-[#9aa3b5]">{tool}</div>
              <div className="mt-1 font-mono text-sm text-[#00e6c3]">{file}</div>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="border-t border-[#1e2533] py-16">
        <h2 className="text-2xl font-bold">Three commands</h2>
        <div className="mt-8 grid gap-4 sm:grid-cols-3">
          {steps.map((s, i) => (
            <div key={s.cmd} className="card rounded-xl p-5">
              <div className="text-xs text-[#7c5cff]">0{i + 1}</div>
              <div className="mt-2 font-mono text-sm text-[#00e6c3]">{s.cmd}</div>
              <p className="mt-3 text-sm text-[#9aa3b5]">{s.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Before / after */}
      <section className="border-t border-[#1e2533] py-16">
        <h2 className="text-2xl font-bold">Edit one file. Mirror the rest.</h2>
        <div className="mt-8 grid items-stretch gap-4 md:grid-cols-2">
          <div className="card overflow-hidden rounded-xl">
            <div className="border-b border-[#1e2533] bg-[#0e1219] px-4 py-2 font-mono text-xs text-[#9aa3b5]">
              AGENTS.md — you edit this
            </div>
            <pre className="overflow-auto p-4 font-mono text-xs leading-6 text-[#aeb6c5]">
              {AGENTS_SAMPLE}
            </pre>
          </div>
          <div className="card overflow-hidden rounded-xl">
            <div className="border-b border-[#1e2533] bg-[#0e1219] px-4 py-2 font-mono text-xs text-[#9aa3b5]">
              CLAUDE.md — generated, never hand-edited
            </div>
            <pre className="overflow-auto p-4 font-mono text-xs leading-6 text-[#aeb6c5]">
              {CLAUDE_SAMPLE}
            </pre>
          </div>
        </div>
      </section>

      {/* Why lean */}
      <section className="border-t border-[#1e2533] py-16">
        <div className="grid items-center gap-8 md:grid-cols-2">
          <div>
            <h2 className="text-2xl font-bold">Lean beats bloated</h2>
            <p className="mt-3 text-[#9aa3b5]">
              Good context files raise agent task success from ~30% to ~90%. But AI-generated
              walls of rules measurably hurt accuracy and cost more tokens. AgentMirror never
              auto-writes rules — it syncs your curated file and lints out the bloat.
            </p>
          </div>
          <div className="card rounded-xl p-6 text-center">
            <div className="text-5xl font-extrabold text-[#00e6c3] glow">~30% → ~90%</div>
            <div className="mt-2 text-sm text-[#9aa3b5]">
              agent task success: no context file → a good, lean one
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-[#1e2533] py-16 text-center">
        <h2 className="text-3xl font-bold">Keep your AGENTS.md honest.</h2>
        <div className="mt-6 flex flex-wrap justify-center gap-3">
          <a
            href={GITHUB}
            className="btn-neon rounded-lg bg-[#00e6c3] px-5 py-2.5 font-semibold text-[#08221e] hover:brightness-110"
          >
            Star on GitHub
          </a>
          <a
            href={MIGRATE}
            className="rounded-lg border border-[#2a3346] px-5 py-2.5 font-semibold text-[#d7dce5] hover:border-[#00e6c3]"
          >
            Migration guide
          </a>
        </div>
      </section>

      <footer className="border-t border-[#1e2533] py-8 text-sm text-[#6b7488]">
        AgentMirror · MIT · Sync is deterministic, no AI. Built on the AGENTS.md standard.
      </footer>
    </div>
  );
}
