/**
 * Every generated mirror opens with this banner so a human (or another agent)
 * immediately knows the file is generated and where the real source lives.
 * It is part of the rendered content, so drift detection compares against it
 * exactly — hand-editing a mirror is therefore reported as drift, as intended.
 */
export const BANNER =
  '<!-- Generated by agentmirror from AGENTS.md. Do not edit directly — edit AGENTS.md and run `agentmirror sync`. -->';

/** Wrap canonical content with the banner and a single trailing newline. */
export function withBanner(content: string): string {
  return `${BANNER}\n\n${content.replace(/\s+$/, '')}\n`;
}

/** Remove a leading AgentMirror banner (used when importing a mirror as a source). */
export function stripBanner(content: string): string {
  return content
    .split(/\r?\n/)
    .filter((line) => line.trim() !== BANNER)
    .join('\n')
    .replace(/^\s+/, '');
}
