import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runInit } from '../src/commands/init';
import { runSync } from '../src/commands/sync';
import { runCheck } from '../src/commands/check';
import { runLint } from '../src/commands/lint';

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'lockstep-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('init', () => {
  it('scaffolds AGENTS.md and config in non-interactive mode', async () => {
    const result = await runInit({ cwd: dir, yes: true, quiet: true });
    expect(existsSync(join(dir, 'AGENTS.md'))).toBe(true);
    expect(existsSync(join(dir, 'lockstep.config.json'))).toBe(true);
    expect(result.targets.length).toBeGreaterThan(0);
  });
});

describe('sync', () => {
  it('writes mirrors with the banner and reports statuses', () => {
    writeFileSync(join(dir, 'AGENTS.md'), '# Demo\n\nBe lean.\n');
    const first = runSync({ cwd: dir, quiet: true });
    expect(first.written.every((w) => w.status === 'created')).toBe(true);

    const claude = readFileSync(join(dir, 'CLAUDE.md'), 'utf8');
    expect(claude).toContain('Generated by lockstep');
    expect(claude).toContain('Be lean.');
    expect(existsSync(join(dir, '.cursor/rules/agents.mdc'))).toBe(true);

    const second = runSync({ cwd: dir, quiet: true });
    expect(second.written.every((w) => w.status === 'unchanged')).toBe(true);
  });

  it('throws a helpful error when the source is missing', () => {
    expect(() => runSync({ cwd: dir, quiet: true })).toThrow(/lockstep init/);
  });
});

describe('check', () => {
  it('passes right after a sync', () => {
    writeFileSync(join(dir, 'AGENTS.md'), '# Demo\n\nText.\n');
    runSync({ cwd: dir, quiet: true });
    expect(runCheck({ cwd: dir, quiet: true }).ok).toBe(true);
  });

  it('detects drift when a mirror is hand-edited', () => {
    writeFileSync(join(dir, 'AGENTS.md'), '# Demo\n\nText.\n');
    runSync({ cwd: dir, quiet: true });
    writeFileSync(join(dir, 'CLAUDE.md'), 'tampered\n');
    const result = runCheck({ cwd: dir, quiet: true });
    expect(result.ok).toBe(false);
    expect(result.drift.find((d) => d.path === 'CLAUDE.md')?.status).toBe('drift');
  });

  it('flags stale references to missing files', () => {
    writeFileSync(join(dir, 'AGENTS.md'), '# Demo\n\nEdit `src/ghost.ts`.\n');
    runSync({ cwd: dir, quiet: true });
    const result = runCheck({ cwd: dir, quiet: true });
    expect(result.ok).toBe(false);
    expect(result.stale.some((s) => s.message.includes('src/ghost.ts'))).toBe(true);
  });

  it('accepts references that exist in the repo', () => {
    mkdirSync(join(dir, 'src'));
    writeFileSync(join(dir, 'src', 'real.ts'), '');
    writeFileSync(join(dir, 'package.json'), JSON.stringify({ scripts: { build: 'tsup' } }));
    writeFileSync(join(dir, 'AGENTS.md'), '# Demo\n\nEdit `src/real.ts`, run `npm run build`.\n');
    runSync({ cwd: dir, quiet: true });
    expect(runCheck({ cwd: dir, quiet: true }).ok).toBe(true);
  });
});

describe('lint', () => {
  it('fails on stale references and passes on a lean file', () => {
    writeFileSync(join(dir, 'AGENTS.md'), '# Demo\n\nRun `npm run ghost`.\n');
    expect(runLint({ cwd: dir, quiet: true }).ok).toBe(false);

    writeFileSync(join(dir, 'AGENTS.md'), '# Demo\n\nShort and correct.\n');
    expect(runLint({ cwd: dir, quiet: true }).ok).toBe(true);
  });
});
